apiVersion: apps/v1
kind: Deployment
metadata:
  name: web0
spec:
  replicas: 0
  selector:
    matchLabels:
      app: web0
  template:
    metadata:
      labels:
        app: web0
    spec:
      containers:
      - env:
        - name: MY_CGROUP_MODE
          value: systemd
        image: docker.io/jenkins/jenkins:latest
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 8080
          hostPort: 30080
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 2000m
            memory: 2Gi
        volumeMounts: []
      nodeSelector:
        kubernetes.io/hostname: slave1
      priorityClassName: low-priority
      restartPolicy: Always
      volumes: []
